# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "cargo" # Enable version updates for Rust
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    reviewers:
      - "a-ariff"
    assignees:
      - "a-ariff"
    labels:
      - "dependencies"
      - "rust"
    open-pull-requests-limit: 10
