# Static configuration
api:
  dashboard: true
  insecure: true  # Only for development, remove in production

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik-network
  file:
    filename: /dynamic.yml
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: "ariff.mit@gmail.com"
      storage: /ssl/acme.json
      httpChallenge:
        entryPoint: web

# Enable metrics and access logs
metrics:
  prometheus:
    addRoutersLabels: true

accessLog:
  format: json

log:
  level: INFO
